apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: enterprise-gateway
    meta.helm.sh/release-namespace: enterprise-gateway
  labels:
    app: enterprise-gateway
    app.kubernetes.io/managed-by: Helm
    chart: enterprise-gateway-3.2.3
    component: enterprise-gateway
    gateway-selector: enterprise-gateway
    heritage: Helm
    release: enterprise-gateway
  name: enterprise-gateway
  namespace: enterprise-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      gateway-selector: enterprise-gateway
  template:
    metadata:
      labels:
        app: enterprise-gateway
        component: enterprise-gateway
        gateway-selector: enterprise-gateway
    spec:
      containers:
        - env:
            - name: EG_PORT
              value: "8888"
            - name: EG_RESPONSE_PORT
              value: "8877"
            - name: EG_NAMESPACE
              value: enterprise-gateway
            - name: EG_KERNEL_CLUSTER_ROLE
              value: kernel-controller
            - name: EG_SHARED_NAMESPACE
              value: "True"
            - name: EG_MIRROR_WORKING_DIRS
              value: "False"
            - name: EG_CULL_INTERVAL
              value: "60"
            - name: EG_CULL_IDLE_TIMEOUT
              value: "300"
            - name: EG_CULL_CONNECTED
              value: "True"
            - name: EG_LOG_LEVEL
              value: DEBUG
            - name: EG_KERNEL_LAUNCH_TIMEOUT
              value: "300"
            - name: EG_KERNEL_INFO_TIMEOUT
              value: "300"
            - name: EG_KERNEL_RCONNECT_TIMEOUT
              value: "120"
            # - name: EG_ALLOWED_KERNELS
            #   value: '["r_kubernetes","python_kubernetes","python_tf_kubernetes","python_tf_gpu_kubernetes","scala_kubernetes","spark_r_kubernetes","spark_python_kubernetes","spark_scala_kubernetes","spark_python_operator","tf_gpu_sharing","pytorch_gpu_sharing"]'
            - name: EG_DEFAULT_KERNEL_NAME
              value: python_kubernetes
            - name: EG_INHERITED_ENVS
              value: PATH
          image: elyra/enterprise-gateway:3.2.3
          imagePullPolicy: IfNotPresent
          name: enterprise-gateway
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8877
              protocol: TCP
          volumeMounts:
            - name: shared-kernels
              mountPath: /usr/local/share/jupyter/kernels
      restartPolicy: Always
      securityContext: {}
      serviceAccount: enterprise-gateway-sa
      serviceAccountName: enterprise-gateway-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: shared-kernels
          persistentVolumeClaim:
            claimName: kernel-specs-pvc