apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name2
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.repositoryUrl
  targets:
  - select:
      kind: ResourceQuota
    fieldPaths:
    - metadata.labels.repositoryUrl
