apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: stateful-migration/checkpoint-apiserver
  name: checkpoint-apiserver
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: checkpoint-apiserver
    app.kubernetes.io/part-of: stateful-migration-operator
    app.kubernetes.io/component: apiserver
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|stateful-migration|checkpoint-apiserver'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkpoint-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkpoint-apiserver
        app.kubernetes.io/part-of: stateful-migration-operator
        app.kubernetes.io/component: apiserver
    spec:
      serviceAccountName: checkpoint-apiserver-sa
      containers:
      - name: apiserver
        image: docker.io/vitu1/checkpoint-apiserver:v1
        imagePullPolicy: IfNotPresent
        command:
        - /apiserver
        args:
        - --bind-address=:8090
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      terminationGracePeriodSeconds: 15
