apiVersion: v1
kind: Service
metadata:
  name: checkpoint-apiserver
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: checkpoint-apiserver
    app.kubernetes.io/part-of: stateful-migration-operator
    app.kubernetes.io/component: apiserver
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: checkpoint-apiserver
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
    nodePort: 30829
