apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-dr
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: dr
    repo: catalog-nephio-optional
    revision: v2.0.0
  downstream:
    package: example-dr
    repo: dr
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
