apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 1m
  releaseName: gpu-operator
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: gpu-operator
  valuesFrom:
  - kind: ConfigMap
    name: gpu-operator-values
    valuesKey: values.yaml
