apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app: nfs-provisioner
    app.kubernetes.io/name: nfs-provisioner
    app.kubernetes.io/part-of: kubeflow
    istio-injection: disabled

