apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: pkg-free5gc-webui
  package-path: free5gc-workload/pkg-free5gc-webui
