apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: free5gc
  mongodb-uri: mongodb://mongodb:27017
  image-webui: free5gc/webui:v3.4.3
  service-type: NodePort
  node-port: "30500"
