apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-config
  namespace: free5gc # kpt-set: ${namespace}
data:
  webuicfg.yaml: |
    info:
      version: 1.0.3
      description: WebUI initial local configuration
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017
      nrfUri: https://nrf-service:8000
      webServer:
        scheme: http
        ipv4Address: 0.0.0.0
        port: 5000
      billingServer:
        enable: true
        hostIPv4: 127.0.0.1
        port: 2122
        scheme: http
        basePath: /
        listenPort: 2122
        portRange:
          start: 2122
          end: 2122
    logger:
      enable: true
      level: info
      reportCaller: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: free5gc # kpt-set: ${namespace}
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: free5gc/webui:v3.4.3 # kpt-set: ${image-webui}
          imagePullPolicy: IfNotPresent
          workingDir: /free5gc
          command: ["/free5gc/webui"]
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017 # kpt-set: ${mongodb-uri}
            - name: GIN_MODE
              value: release
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: webui-config
              mountPath: /free5gc/config/webuicfg.yaml
              subPath: webuicfg.yaml
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: webui-config
          configMap:
            name: webui-config
---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: free5gc # kpt-set: ${namespace}
  labels:
    app: webui
spec:
  type: NodePort # kpt-set: ${service-type}
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500 # kpt-set: ${node-port}
