apiVersion: v1
kind: Secret
metadata:
  name: reg-credentials
  namespace: default
stringData:
  password: changeme # change to your dockerhub password or access token
  registry: docker.io
  username: vitu1 # change to your dockerhub username
type: Opaque
