apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: default
stringData:
  GIT_SECRET_NAME: git-user-secret
  GIT_SECRET_NAMESPACE: default
  GIT_SERVER_URL: http://54.255.162.223:31416 # change to your git server url
type: Opaque