apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: transition-operator-system
stringData:
  MINIO_ACCESS_KEY: nephio1234 # change to your minio access key
  MINIO_BUCKET: checkpoints  # change to your minio bucket name
  MINIO_ENDPOINT: 54.255.162.223:32001 # change to your minio endpoint
  MINIO_SECRET_KEY: secret1234 # change to your minio secret key
type: Opaque
