apiVersion: v1
kind: Service
metadata:
  name: ml-platform-admin-etcd-headless
  namespace: ml-platform-system
  labels:
    app: ml-platform-admin-etcd
spec:
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: server
      port: 2380
      targetPort: 2380
  selector:
    app: ml-platform-admin-etcd
  clusterIP: None
  publishNotReadyAddresses: true