apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-admin-configmap-example
  namespace: ml-platform-system
data:
  dev.yaml: |-
    docker_registries: []
    chart_registries: []
    gpu_config:
      total_vram_gib: 24
      slice_size_gib: 4
      default_slices: 1
    menu_configs:
      - path: /overview
        enable: true
        sidebar_key: OVERVIEW
      - path: /users
        enable: true
        sidebar_key: USERS
      - path: /profile-manage
        enable: true
        sidebar_key: PROFILES-MANAGEMENT
        children:
          - path: /profile-manage/users
            enable: true
            sidebar_key: USERS
          - path: /profile-manage/priority
            enable: true
            sidebar_key: PRIORITY
          - path: /profile-manage/quota
            enable: true
            sidebar_key: QUOTA
  prod.yaml: |-
    docker_registries: [ ]
    chart_registries: [ ]
    gpu_config:
      total_vram_gib: 24
      slice_size_gib: 4
      default_slices: 1
    menu_configs:
      - path: /overview
        enable: true
        sidebar_key: OVERVIEW
      - path: /users
        enable: true
        sidebar_key: USERS
      - path: /infra-manage
        enable: true
        sidebar_key: INFRA-MANAGE
        children:
          - path: /infra-manage/clusters
            enable: true
            sidebar_key: CLUSTER-MANAGE
          - path: /infra-manage/cloud-credentials
            enable: true
            sidebar_key: CLOUD-CREDENTIALS
      - path: /profile-manage
        enable: true
        sidebar_key: PROFILES-MANAGEMENT
        children:
          - path: /profile-manage/users
            enable: true
            sidebar_key: USERS
          - path: /profile-manage/priority
            enable: true
            sidebar_key: PRIORITY
          - path: /profile-manage/quota
            enable: true
            sidebar_key: QUOTA
      - path: /basic-config
        enable: true
        sidebar_key: BASIC-CONFIG
        children:
          - path: monitoring-config
            enable: true
            sidebar_key: MONITORING-CONFIG
