apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    transition.dcnlab.ssu.ac.kr/cluster-policy: "true"
    transition.dcnlab.ssu.ac.kr/packageName: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          args:
            - redis-server
            # Disable persistence for stateless checkpoint
            - --save
            - ""
            - --appendonly
            - "no"

            # Safe network rebinding after restore
            - --protected-mode
            - "no"
            - --bind
            - "0.0.0.0"
            - --port
            - "6379"

            # Prevent io_uring / multi-thread I/O conflicts
            - --io-threads
            - "1"
            - --io-threads-do-reads
            - "no"

            # Logging to stdout for restore diagnostics
            - --logfile
            - ""
            - --loglevel
            - "notice"