apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort  # Change service type to NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30081  # Optional: Specify a NodePort in the range 30000–32767
  selector:
    app: redis
