apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kernel-specs-pvc
  namespace: enterprise-gateway
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi