apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  # type: oci
  interval: 1m
  url: https://vmware-tanzu.github.io/helm-charts
