apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hami-webui
  namespace: kube-system
spec:
  interval: 5m
  releaseName: hami-webui
  chart:
    spec:
      chart: hami-webui
      sourceRef:
        kind: HelmRepository
        name: hami-webui
        namespace: kube-system

  values:
    service:
      type: NodePort
      port: 3000
      nodePort: 30181   # optional

    externalPrometheus:
      enabled: true
      address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

    env:
      frontend:
        - name: TZ
          value: "Asia/Seoul"
      backend:
        - name: TZ
          value: "Asia/Seoul"

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3