apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/kourier-system/Deployment/3scale-kourier-gateway
data:
  ingress-class: kourier.ingress.networking.knative.dev
