apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kueue
  namespace: kueue-system
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: kueue
    namespace: kueue-system
  valuesFrom:
  - kind: ConfigMap
    name: kueue-values
    valuesKey: values.yaml
