apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloud-provider-azure
  namespace: flux-system

spec:
  interval: 1h

  url: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo