apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow
  namespace: flux-system
spec:
  interval: 10m
  path: "./example"
  prune: true
  wait: true
  timeout: 30m

  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
