apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  interval: 10m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: kubeflow-helm
        namespace: kubeflow
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: kubeflow-values
  #     optional: true
