apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: kubeflow
  path: "./example"
  prune: true
  timeout: 1m