apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  interval: 5m
  url: https://github.com/kubeflow/manifests
  ref:
    branch: master