apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hami-dra-chart
  namespace: kube-system
spec:
  interval: 5m
  url: https://github.com/vitu-mafeni/HAMi-DRA
  ref:
    tag: hami-dra-0.2.1-fix1