apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hami-dra
  namespace: kube-system
spec:
  interval: 5m
  releaseName: hami-dra
  chart:
    spec:
      chart: ./charts/hami-dra
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: hami-dra-chart
        namespace: kube-system

  values:
    # scheduler:
    #   kubeScheduler:
    #     # ⚠️ MUST match your Kubernetes version exactly
    #     # replace this with your actual version
    #     imageTag: v1.34.0
    monitor:
      enabled: true
      service:
        type: NodePort
        nodePort:
          metrics: 31995

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3