apiVersion: v1
kind: Namespace
metadata:
  name: kai-scheduler
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"
---
kind: ConfigMap
metadata:
  name: kai-scheduler-values
  namespace: kai-scheduler
apiVersion: v1
data:
  values.yaml: |
    # Default values for kai-scheduler.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # Copyright 2025 NVIDIA CORPORATION
    # SPDX-License-Identifier: Apache-2.0
    global:
      gpuSharing: true
    admission:
      gpuPodRuntimeClassName: nvidia-cdi
    binder:
      cdiEnabled: true
      resourceReservation:
        runtimeClassName: nvidia-cdi