apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: # kpt-merge: kueue-system/kueue
  name: kai-scheduler
  namespace: kai-scheduler
spec:
  interval: 1m
  releaseName: kai-scheduler
  chart:
    spec:
      chart: charts/kai-scheduler
      sourceRef:
        kind: GitRepository
        name: kai-scheduler
        namespace: kai-scheduler
  valuesFrom:
  - kind: ConfigMap
    name: kai-scheduler-values
    valuesKey: values.yaml
