apiVersion: v1
kind: ConfigMap
metadata:
  name: gnb-config
  namespace: free5gc # kpt-set: ${namespace}
data:
  gnb.yaml: |
    mcc: '001'  # kpt-set: ${plmn-mcc}
    mnc: '01'   # kpt-set: ${plmn-mnc}
    nci: '0x000000010'
    idLength: 32
    tac: 1  # kpt-set: ${tac}
    cellBarred: false
    linkIp: 192.168.10.204  # kpt-set: ${gnb-n2-ip}
    ngapIp: 192.168.10.204  # kpt-set: ${gnb-n2-ip}
    gtpIp: 192.168.12.205   # kpt-set: ${gnb-n3-ip}
    amfConfigs:
      - address: 192.168.10.200  # kpt-set: ${amf-n2-ip}
        port: 38412
    slices:
      - sst: 1
        sd: '010203'
    ignoreStreamIds: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnb
  namespace: free5gc # kpt-set: ${namespace}
  labels:
    app: gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnb
  template:
    metadata:
      labels:
        app: gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-gnb-n2, free5gc-gnb-n3
    spec:
      nodeName: ip-192-168-1-57.ap-northeast-2.compute.internal # kpt-set: ${edge-worker-node}
      containers:
        - name: gnb
          image: free5gc/ueransim:v3.4.3 # kpt-set: ${image-ueransim}
          command: ["/ueransim/nr-gnb", "-c", "/ueransim/config/gnb.yaml"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: gnb-config
              mountPath: /ueransim/config/
      volumes:
        - name: gnb-config
          configMap:
            name: gnb-config
---
apiVersion: v1
kind: Service
metadata:
  name: gnb-service
  namespace: free5gc # kpt-set: ${namespace}
  labels:
    app: gnb
spec:
  type: ClusterIP
  selector:
    app: gnb
  ports:
    - name: gnb-sctp
      protocol: SCTP
      port: 38412
      targetPort: 38412
