apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: aws-nephio-md-0
  namespace: default
spec:
  template:
    spec:
      preKubeadmCommands:
        - |
          # Get the primary local IP
          LOCAL_IP=$(hostname -I | awk '{print $1}')
          # Download containerd
          curl -LO https://github.com/containerd/containerd/releases/download/v2.1.4/containerd-2.1.4-linux-amd64.tar.gz

          # Extract containerd to a temporary directory
          mkdir -p /tmp/containerd
          tar -xzf containerd-2.1.4-linux-amd64.tar.gz -C /tmp/containerd

          # Stop kubelet and containerd services safely
          systemctl stop kubelet || true
          systemctl stop containerd || true

          # Kill any lingering containerd shim processes
          pkill -9 containerd-shim-runc-v2 || true

          # Copy only containerd binaries explicitly to /usr/local/bin
          cp -f /tmp/containerd/bin/containerd /usr/local/bin/
          cp -f /tmp/containerd/bin/ctr /usr/local/bin/
          cp -f /tmp/containerd/bin/containerd-shim /usr/local/bin/

          # Re-execute systemd daemon and start containerd
          systemctl daemon-reexec
          systemctl start containerd
        - |
          # Install CRIU
          curl -fsSL https://download.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_22.04/Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/criu.gpg
          echo "deb http://download.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_22.04/ ./" | tee /etc/apt/sources.list.d/criu.list
          apt-get update
          apt-get install criu -y

          # Upgrade runc
          cd /tmp
          curl -L -o runc.new https://github.com/opencontainers/runc/releases/download/v1.3.1/runc.amd64
          mv /tmp/runc.new /usr/local/sbin/runc
          chmod +x /usr/local/sbin/runc

          # Create CRIU config
          mkdir -p /etc/criu
          printf '%s\n' \
            'file-locks' \
            'tcp-close' \
            'skip-in-flight' \
            'tcp-established' \
            'log-file /tmp/criu.log' \
            '' \
            'enable-external-masters' \
            'external mnt[]' \
            'skip-mnt /proc/latency_stats' \
            > /etc/criu/runc.conf
          systemctl restart kubelet containerd

      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            node-ip: '{{ ds.meta_data.local_ipv4 }}'
          name: '{{ ds.meta_data.local_hostname }}'
