apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: free5gc # kpt-set: ${namespace}
data:
  udmcfg.yaml: |
    info:
      version: 1.0.3
      description: UDM initial local configuration
    configuration:
      serviceNameList:
        - nudm-sdm
        - nudm-uecm
        - nudm-ueau
        - nudm-ee
        - nudm-pp
      sbi:
        scheme: https
        registerIPv4: udm-service
        bindingIPv4: 0.0.0.0
        port: 8000
        tls:
          key: cert/udm.key
          pem: cert/udm.pem
      nrfUri: https://nrf-service:8000 # kpt-set: ${nrf-service-name}
    logger:
      enable: true
      level: info
      reportCaller: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: free5gc # kpt-set: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      initContainers:
      - name: wait-udr
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zw3 udr-service.free5gc.svc.cluster.local 8000; do echo waiting for udr; sleep 2; done']
      containers:
      - name: udm
        image: free5gc/udm:v3.4.3 # kpt-set: ${image-udm}
        imagePullPolicy: IfNotPresent
        command: ["./udm", "-c", "/free5gc/config/udmcfg.yaml"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/udmcfg.yaml
          subPath: udmcfg.yaml
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: config
        configMap:
          name: udm-config
---
apiVersion: v1
kind: Service
metadata:
  name: udm-service
  namespace: free5gc # kpt-set: ${namespace}
spec:
  selector:
    app: udm
  ports:
  - name: sbi
    port: 8000
    targetPort: 8000
