apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: free5gc # kpt-set: ${namespace}
data:
  udrcfg.yaml: |
    info:
      version: 1.1.0
      description: UDR initial local configuration
    configuration:
      sbi:
        scheme: https
        registerIPv4: udr-service
        bindingIPv4: 0.0.0.0
        port: 8000
        tls:
          key: cert/udr.key
          pem: cert/udr.pem
      dbConnectorType: mongodb
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017
      nrfUri: https://nrf-service:8000 # kpt-set: ${nrf-service-name}
      serviceNameList:
        - nudr-dr
    logger:
      enable: true
      level: info
      reportCaller: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: free5gc # kpt-set: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      initContainers:
      - name: wait-nrf
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zw3 nrf-service.free5gc.svc.cluster.local 8000; do echo waiting for nrf; sleep 2; done']
      containers:
      - name: udr
        image: free5gc/udr:v3.4.3 # kpt-set: ${image-udr}
        imagePullPolicy: IfNotPresent
        command: ["./udr", "-c", "/free5gc/config/udrcfg.yaml"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /free5gc/config/udrcfg.yaml
          subPath: udrcfg.yaml
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: config
        configMap:
          name: udr-config
---
apiVersion: v1
kind: Service
metadata:
  name: udr-service
  namespace: free5gc # kpt-set: ${namespace}
spec:
  selector:
    app: udr
  ports:
  - name: sbi
    port: 8000
    targetPort: 8000
