apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
  valuesFrom:
  - kind: ConfigMap
    name: kyverno-values
    valuesKey: values.yaml
