apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth
spec:
  selector:
    app.kubernetes.io/instance: kubeflow-dex
  ports:
  - name: dex
    port: 5556
    targetPort: 5556
    nodePort: 32269
  type: NodePort